### ISSUE TITLE
Syntax error in Python 3.4 egg

### ISSUE THREAD

**Issue by robclewley** [ezag/pyeuclid#11] opened 2015-05-14 14:38 UTC
In the version currently available from PyPI:

euclid.py: line 137
`raise  AttributeError, name` is an invalid way to raise an exception in Python 3. Should be `raise  AttributeError(name)` as it is in the current repo version. Haven't checked for other occurrences of this, but this is the first that comes up when trying to import.

 Can the PyPI version be refreshed?

**Comment by ezag** [comment] 2016-09-15 23:14
Duplicate of #8

**Closed by ezag** 2016-09-15 23:14 UTC
